theme: jekyll-theme-minimal
title: 350 Алгоритми та структури даних
description: Конспекти лекцій та Лабораторні роботи з дисципліни "Алгоритми та структури даних" для III курсу спеціальності 121 "Інженерія програмного забезпечення" ОКР "Фаховий молодший бакалавр" Херсонського політехнічного фахового коледжу Державного університету "Одеська політехніка"
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge